-- AlterTable
ALTER TABLE `courier` ADD COLUMN `auto_accept` TINYINT NOT NULL DEFAULT 0,
    ADD COLUMN `max_orders` INTEGER NOT NULL DEFAULT 10,
    ADD COLUMN `on_route` TINYINT NOT NULL DEFAULT 0,
    ADD COLUMN `online` TINYINT NOT NULL DEFAULT 0,
    ADD COLUMN `priority` INTEGER NOT NULL DEFAULT 100;
